# Generated by Django 5.0.6 on 2024-07-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='emaildeexemplo@email.com', max_length=254),
        ),
    ]
