# Generated by Django 5.0.6 on 2024-07-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0003_usuario_codigo_hex_alter_usuario_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_hex',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, default='Not provided', max_length=100, null=True),
        ),
    ]
