# Generated by Django 5.0.6 on 2024-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0005_usuario_codigo_hex_alter_usuario_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_hex',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, default='Not provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='emaildeexemplo@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20),
        ),
    ]
