# Generated by Django 5.0.6 on 2024-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0006_remove_usuario_codigo_hex_alter_usuario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
